# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
name: "Setup and validate environment"

inputs:
  working-directory:
    description: 'The directory that steps should be executed in'
    default: './'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - uses: 'moonrepo/setup-toolchain@v0.6'
      with:
        auto-install: true
    - name: Load secrets
      id: load-secrets
      uses: 1password/load-secrets-action@v3
      env:
        CLOUDFLARE_ACCESS_KEY_ID: op://Valheim/tf-valheim/access_key_id
        CLOUDFLARE_SECRET_ACCESS_KEY: op://Valheim/tf-valheim/secret_access_key
        CLOUDFLARE_ENDPOINT_URL_S3: op://Valheim/tf-valheim/s3_endpoint

    - name: Terraform Format check
      id: fmt
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -check
      shell: bash

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
      shell: bash
      with:
        AWS_ACCESS_KEY_ID: ${{ steps.load-secrets.outputs.CLOUDFLARE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.load-secrets.outputs.CLOUDFLARE_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ steps.load-secrets.outputs.CLOUDFLARE_ENDPOINT_URL_S3 }}

    - name: Terraform Validate
      id: validate
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate -no-color
      shell: bash