# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
name: "Setup and validate environment"

inputs:
  working-directory:
    description: 'The directory that steps should be executed in'
    default: './'

runs:
  using: composite
  steps:
    # ensure checkout step is run before calling this action
    - uses: 'moonrepo/setup-toolchain@v0.6'
      with:
        auto-install: true
